# This workflow will install Python dependencies and run tests for computing code coverage
# Results will be uploaded to codecov

name: Code Coverage

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ development ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate coverage report
      run: |
        pytest tests/test_aggregate.py --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        version: "v0.1.15"
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
