# This workflow will package the Python framework and upload it to PyPI

name: Package Release

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build --user
    - name: Build wheel and source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
